spring:
  datasource:
    url: jdbc:postgresql://localhost:5434/demo
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: validate # или update / create / none
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect

  application:
    name: security

  app:
    - jwtSecret=mySecretKey123912738aopsgjnspkmndfsopkvajoirjg94gf2opfng2moknm
    - jwtExpirationMs=3000000

logging:
  level:
    org:
      - springframework: DEBUG
      - hibernate.sql: DEBUG
      - springframework.security: DEBUG
      - security: DEBUG
